FROM alpine:3.5
RUN apk add --update ruby ruby-bundler ruby-dev build-base \
  && gem install bundler --no-ri --no-rdoc
ENV APP_HOME=/app \
  POST_SERVICE_HOST=post \
  POST_SERVICE_PORT=5000 \
  COMMENT_SERVICE_HOST=comment \
  COMMENT_SERVICE_PORT=9292
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY . $APP_HOME
RUN bundle install

CMD ["puma"]
